{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cf4k8s.serviceAccountName" . }}
  labels:
{{ include "cf4k8s.labels" . | indent 4 }}
{{- end -}}
