---
apiVersion: v1
kind: Namespace
metadata:
  name: install-cf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wide-open-for-cf4k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind:      ServiceAccount
    namespace: install-cf
    name:      default
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: install-cf
  name:      install-cf4k8s
spec:
  backoffLimit: 2

  template:
    spec:
      restartPolicy: Never

      volumes:
        - name: cf-values
          configMap:
            name: cf-values

      containers:
        - name:  install
          image: starkandwayne/install-cf4k8s:1.0.0
          imagePullPolicy: Always

          volumeMounts:
            - name: cf-values
              mountPath: /etc/cf

          env:
            - name:  CF_VALUES_FROM
              value: /etc/cf/cf-values.yml
